[stability]

[[stability.tests]]
file = "src/system_tests/e2e/fast_test.py"
cases = [
    "TestServerStreamFast::test_get_top_account_by_revenue_stream_fast",
    "TestServerStreamFast::test_list_my_accounts_fast",
    "TestServerStreamFast::test_find_vp_sales_active_high_value_accounts_fast"
]

[[stability.tests]]
file = "src/system_tests/e2e/crm_contacts_email_test.py"
cases = [
    "TestCRMContactsEmailWorkflow::test_crm_contacts_write_and_email"
]


[[stability.tests]]
file = "src/system_tests/e2e/crm_hf_utterances_test.py"
cases = [
    "TestCRMHF_Examples::test_get_top_n_accounts_revenue",
    "TestCRMHF_Examples::test_filter_contacts_and_calculate_revenue_percentile",
    "TestCRMHF_Examples::test_show_users_in_crm_system",
    "TestCRMHF_Examples::test_what_is_cuga",
    "TestCRMHF_Examples::test_playbook_execution"
]
